/**
 * Mock places dataset for AI KumbhMitra (Nashik + Trimbakeshwar)
 * 
 * DISCLAIMER:
 * This is demonstration data created for the Phase 1 UI shell.
 * Phone numbers, opening hours, ratings, and details are mock placeholders
 * and must NOT be interpreted as real or officially verified Kumbh 2027 data.
 */

export const PLACE_CATEGORIES = [
  { id: 'all', label: 'All Places', icon: '📍' },
  { id: 'temple', label: 'Temples', icon: '🛕' },
  { id: 'ghat', label: 'Ghats', icon: '🌊' },
  { id: 'hotel', label: 'Hotels', icon: '🏨' },
  { id: 'restaurant', label: 'Restaurants', icon: '🍛' },
  { id: 'shop', label: 'Shops', icon: '🏪' },
  { id: 'hospital', label: 'Hospitals', icon: '🏥' },
  { id: 'parking', label: 'Parking', icon: '🅿️' },
  { id: 'police', label: 'Police', icon: '🚓' },
  { id: 'medical', label: 'Medical', icon: '🚑' },
  { id: 'transport', label: 'Transport', icon: '🚌' },
  { id: 'tourist', label: 'Tourist Places', icon: '📍' }
];

export const MOCK_PLACES = [
  {
    id: 'place_trimbakeshwar',
    name: 'Trimbakeshwar Shiva Temple',
    category: 'temple',
    categoryLabel: 'Temple',
    categoryIcon: '🛕',
    region: 'Trimbakeshwar',
    tagline: 'Ancient Jyotirlinga shrine at the origin of sacred Godavari River',
    description: 'One of the twelve sacred Jyotirlingas, featuring a three-faced linga representing Brahma, Vishnu, and Shiva. Major pilgrimage destination during Simhastha Kumbh Mela.',
    imagePlaceholder: 'linear-gradient(135deg, #f97316 0%, #c2410c 100%)',
    address: 'Trimbak, Western Ghats Foothills, Nashik District, Maharashtra 422212',
    phone: '+91 2594 233 215 (Demo Placeholder)',
    openingHours: '05:30 AM – 09:00 PM (Demonstration Data)',
    rating: 4.8,
    reviewsCount: '24,500+ (Demo)',
    accessibility: 'Wheelchair ramp available at North Gate; Special assistance booth active.',
    latitude: 19.9325,
    longitude: 73.5308,
    coordinatesSummary: '19.9325° N, 73.5308° E',
    tags: ['Jyotirlinga', 'Sacred Snan', 'Ancient Architecture', 'Kumbh Core Point'],
    mapPosition: { top: '38%', left: '26%' }
  },
  {
    id: 'place_ramkund',
    name: 'Ramkund Panchavati',
    category: 'ghat',
    categoryLabel: 'Ghat',
    categoryIcon: '🌊',
    region: 'Nashik',
    tagline: 'Sacred bathing ghat on the banks of holy Godavari River',
    description: 'The holiest bathing ghat in Nashik where Lord Rama is believed to have performed rituals during exile. Epicenter of the holy Shahi Snan during the Kumbh Mela.',
    imagePlaceholder: 'linear-gradient(135deg, #0284c7 0%, #0369a1 100%)',
    address: 'Panchavati, Godavari Riverbank, Nashik, Maharashtra 422003',
    phone: '+91 253 257 0000 (Demo Placeholder)',
    openingHours: 'Open 24 Hours (Demonstration Data)',
    rating: 4.7,
    reviewsCount: '18,900+ (Demo)',
    accessibility: 'Paved ghat steps with safety barricades, low-mobility holding platform.',
    latitude: 20.0063,
    longitude: 73.7915,
    coordinatesSummary: '20.0063° N, 73.7915° E',
    tags: ['Holy Dip', 'Shahi Snan', 'Godavari Aarti', 'Panchavati'],
    mapPosition: { top: '46%', left: '62%' }
  },
  {
    id: 'place_kalaram',
    name: 'Kalaram Temple',
    category: 'temple',
    categoryLabel: 'Temple',
    categoryIcon: '🛕',
    region: 'Nashik',
    tagline: 'Historic black stone temple dedicated to Lord Rama',
    description: 'Built in 1788 by Sardar Rangrao Odhekar, this majestic black basalt stone temple stands inside the Panchavati heritage corridor.',
    imagePlaceholder: 'linear-gradient(135deg, #d97706 0%, #b45309 100%)',
    address: 'Panchavati Main Chowk, Nashik, Maharashtra 422003',
    phone: '+91 253 251 1234 (Demo Placeholder)',
    openingHours: '05:00 AM – 10:00 PM (Demonstration Data)',
    rating: 4.6,
    reviewsCount: '9,200+ (Demo)',
    accessibility: 'Step ramps at East Entry; seating arrangements inside courtyard.',
    latitude: 20.0075,
    longitude: 73.7942,
    coordinatesSummary: '20.0075° N, 73.7942° E',
    tags: ['Historic Stone', 'Panchavati', 'Heritage', 'Ramayana Trail'],
    mapPosition: { top: '42%', left: '68%' }
  },
  {
    id: 'place_civil_hospital',
    name: 'Nashik District Civil Hospital',
    category: 'hospital',
    categoryLabel: 'Hospital',
    categoryIcon: '🏥',
    region: 'Nashik',
    tagline: '24x7 Multi-specialty government emergency hospital',
    description: 'Apex public healthcare facility equipped with 24-hour trauma care, intensive care units, emergency ambulances, and a dedicated Kumbh surge medical wing.',
    imagePlaceholder: 'linear-gradient(135deg, #dc2626 0%, #991b1b 100%)',
    address: 'Trimbak Road, Near Police Headquarters, Nashik, Maharashtra 422002',
    phone: '+91 253 257 6106 (Demo Placeholder)',
    openingHours: 'Emergency Open 24/7 (Demonstration Data)',
    rating: 4.3,
    reviewsCount: '1,450+ (Demo)',
    accessibility: 'Fully wheelchair accessible, stretcher ramps, dedicated emergency triage.',
    latitude: 19.9912,
    longitude: 73.7786,
    coordinatesSummary: '19.9912° N, 73.7786° E',
    tags: ['24x7 Trauma', 'Emergency Care', 'Ambulance Base', 'Civil Hospital'],
    mapPosition: { top: '64%', left: '54%' }
  },
  {
    id: 'place_hotel_panchavati',
    name: 'Hotel Panchavati Yatri',
    category: 'hotel',
    categoryLabel: 'Hotel',
    categoryIcon: '🏨',
    region: 'Nashik',
    tagline: 'Popular lodging and vegetarian dining near pilgrimage hubs',
    description: 'Renowned mid-scale hospitality facility offering family lodging, purified drinking facilities, luggage storage, and traditional Maharashtrian sattvic meals.',
    imagePlaceholder: 'linear-gradient(135deg, #4f46e5 0%, #3730a3 100%)',
    address: '430 Vakil Wadi, MG Road, Nashik, Maharashtra 422001',
    phone: '+91 253 257 2290 (Demo Placeholder)',
    openingHours: 'Check-in 12:00 PM / 24-hr Front Desk (Demonstration Data)',
    rating: 4.4,
    reviewsCount: '3,800+ (Demo)',
    accessibility: 'Elevator access to all room levels; level ground reception.',
    latitude: 19.9975,
    longitude: 73.7854,
    coordinatesSummary: '19.9975° N, 73.7854° E',
    tags: ['Family Lodging', 'Pure Vegetarian', 'City Center', 'Luggage Cloakroom'],
    mapPosition: { top: '56%', left: '58%' }
  },
  {
    id: 'place_saraf_bazar',
    name: 'Saraf Bazar Heritage Brass & Pooja Articles',
    category: 'shop',
    categoryLabel: 'Shop',
    categoryIcon: '🏪',
    region: 'Nashik',
    tagline: 'Traditional bazaar for brass idols, copper vessels & religious offerings',
    description: 'Historic vibrant commercial lane near the Godavari River featuring handcrafted brassware, copper water kalash, organic incense, and Kumbh commemorative artifacts.',
    imagePlaceholder: 'linear-gradient(135deg, #059669 0%, #047857 100%)',
    address: 'Old Nashik Saraf Lane, near Bhadrakali, Nashik, Maharashtra 422001',
    phone: '+91 253 250 9988 (Demo Placeholder)',
    openingHours: '10:00 AM – 09:30 PM (Demonstration Data)',
    rating: 4.5,
    reviewsCount: '2,100+ (Demo)',
    accessibility: 'Narrow pedestrian bazaar street; best navigated on foot.',
    latitude: 20.0011,
    longitude: 73.7882,
    coordinatesSummary: '20.0011° N, 73.7882° E',
    tags: ['Pooja Supplies', 'Brass Artifacts', 'Heritage Market', 'Copper Ware'],
    mapPosition: { top: '50%', left: '60%' }
  },
  {
    id: 'place_cbs_transit',
    name: 'Central Bus Station (CBS) Transit Terminal',
    category: 'transport',
    categoryLabel: 'Transport',
    categoryIcon: '🚌',
    region: 'Nashik',
    tagline: 'Major intercity and ring-route shuttle interchange hub',
    description: 'Main Maharashtra State Road Transport Corporation (MSRTC) bus station with frequent shuttle loops directly connecting Nashik city center to Trimbakeshwar holding zones.',
    imagePlaceholder: 'linear-gradient(135deg, #e11d48 0%, #be123c 100%)',
    address: 'Sharanpur Road / CBS Circle, Nashik, Maharashtra 422002',
    phone: '+91 253 257 5258 (Demo Placeholder)',
    openingHours: '24x7 Transit Operations (Demonstration Data)',
    rating: 4.1,
    reviewsCount: '5,600+ (Demo)',
    accessibility: 'Ramped inquiry counters, reserved priority boarding lines.',
    latitude: 19.9950,
    longitude: 73.7745,
    coordinatesSummary: '19.9950° N, 73.7745° E',
    tags: ['Trimbak Shuttle', 'MSRTC Intercity', 'Information Kiosk', 'Lost & Found'],
    mapPosition: { top: '58%', left: '46%' }
  },
  {
    id: 'place_tapovan_parking',
    name: 'Tapovan Outer Holding Parking Lot P1',
    category: 'parking',
    categoryLabel: 'Parking',
    categoryIcon: '🅿️',
    region: 'Nashik',
    tagline: 'Designated satellite parking and feeder bus holding yard',
    description: 'Massive planned outer perimeter vehicle terminal equipped with electronic toll gates, EV charging stations, passenger rest sheds, and frequent zero-emission shuttle departures.',
    imagePlaceholder: 'linear-gradient(135deg, #64748b 0%, #475569 100%)',
    address: 'Tapovan Ring Road, Near Kapil Dhara, Nashik, Maharashtra 422011',
    phone: '+91 253 259 8811 (Demo Placeholder)',
    openingHours: 'Open 24/7 during Kumbh Mela (Demonstration Data)',
    rating: 4.2,
    reviewsCount: '890+ (Demo)',
    accessibility: 'Level paved tarmac, barrier-free shuttle transfer bays.',
    latitude: 20.0090,
    longitude: 73.8185,
    coordinatesSummary: '20.0090° N, 73.8185° E',
    tags: ['Bus Feeder Loop', 'Rest Sheds', 'Security Guarded', 'Heavy Vehicle Entry'],
    mapPosition: { top: '34%', left: '80%' }
  }
];
